name: 🚀 Deploy Bot Telegram - Assistente de Estoque

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11, 3.12]

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Test database initialization
      run: |
        python db/init_db.py
        
    - name: Verify bot structure
      run: |
        python -c "
        import sys
        sys.path.append('.')
        from bot.railway_fotos import *
        print('✅ Bot com FOTOS estrutura verificada!')
        "

  deploy-docs:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
        
  create-release:
    runs-on: ubuntu-latest
    needs: test
    if: startsWith(github.ref, 'refs/tags/v')
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          📸 **Sistema Completo com FOTOS - Deploy Automático**
          
          ✨ **Funcionalidades implementadas:**
          • Cadastro de itens com fotos completo
          • Upload e armazenamento seguro de fotos
          • Busca visual com exibição automática
          • Sistema de catálogo organizado
          • Banco de dados atualizado
          • Documentação completa
          
          🚀 **Deploy pronto para produção!**
          
          📋 **Como usar:**
          1. Configure o TOKEN do bot no Railway/Heroku
          2. Execute: `python bot/railway_fotos.py`
          3. Use `/novoitem` para cadastrar com fotos
          4. Use `/buscar` para busca visual
          
          📖 **Documentação:** [SISTEMA-FOTOS.md](./SISTEMA-FOTOS.md)
        draft: false
        prerelease: false
